# Generated by Django 5.1 on 2024-08-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_category_post_category_post_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(default='Add summary', max_length=255),
        ),
    ]
