# Generated by Django 5.1 on 2024-08-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_post_status_post_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=10),
        ),
    ]
